### ISSUE TITLE
Request: No preselected option

### ISSUE THREAD

**Issue by NebelAI** [0phoff/st-btn-select#2]
Hey,

This custom component is great and I want to use on it in my current project. But the thing is, even if the user has not pressed any option yet, the component will always return an index. That means I can't tell if the button was pressed by the user or not.

**Comment by jeromeroussin** [comment]
Hey, I second this request. Making rows of buttons is suprisingly hard with streamlit right now and this component would address of lot of common usecases if it did not require a default selected option. Thanks!

**Comment by mansidak** [comment]
It's called 'index' and ranges from 0-n. Just set it as one of the params.
